### PR TITLE
Improvement to filterBy

### PR DESCRIPTION
**Pull request by ksnyde**
allows non-existent properties to be considered in comparison rather than be immediately rejected.

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Seems to be conflicts, can you rebase?

**Comment by ksnyde** [comment]
Ooops. Careless on my part.

**Comment by ksnyde** [comment]
Ok I must admit i've never done this procedure with git before. All tests work fine in my repo and I merged in all changes prior to making my one line adjustment. When I check Travis the error is:

> 1) Underscore\Types\StringTest::testCanGetStringLength
Failed asserting that 5 matches expected 15.

not sure what this is but it doesn't appear related to my tests or my one line change. Can you help me make it right?

**Comment by ksnyde** [comment]
Cheers, thanks. BTW, how does one collaborate in making the documentation up-to-date or do you prefer to do this yourself?

**Comment by Anahkiasen** [comment]
The documentation is generated from the wiki, need to update it (or maybe see if you can)

**Pull request merged**
