### PR TITLE
fix composer.json for laravel 5

### PR DESCRIPTION
**Pull request by shnhrrsn**
via @williammck

### CODE REVIEW

**Comment by williammck** [comment]
I'd close this for now. I haven't made much progress on fixing Flickering and Underscore for L5 - there's a few other things that would need to be fixed other than composer.json.

If I have some time soon, I'll take a shot at finishing it.

**Comment by mcordingley** [comment]
Just want to point out #56 fixes this by breaking the dependency on Laravel. The real problem is coupling between a low-level library and a large, high-level project, as explained in #50.

**Comment by newtonianb** [comment]
:+1: please L5 !!!

**Comment by williammck** [comment]
As @mcordingley pointed out, #50 and #56 should really be pulled in. @Anahkiasen - you around? Would like for this to get fixed.

**Comment by Anahkiasen** [comment]
Closed in favor of #56

**Pull request closed without merging**
