### PR TITLE
A few refactoring

### PR DESCRIPTION
**Pull request by sergiors**

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Thanks!

**Comment by sergiors** [comment]
Hey @Anahkiasen, I seen `~/Methods/ArraysMethods` and I think to use Type Hinting could be better.

```php
 public static function flatten($array, $separator = '.', $parent = null)
 {
        if (!is_array($array)) {
            return $array;
        }
```

Could be
```php
 public static function flatten(array $array, $separator = '.', $parent = null)
```

**Comment by Anahkiasen** [comment]
Hm I think this was here for chaining when you juggle multiple types IIRC

**Comment by sergiors** [comment]
I got it

**Pull request merged**
