### PR TITLE
Remove Illuminate Dependency

### PR DESCRIPTION
**Pull request by mcordingley**
See #50 for the rationale.

### CODE REVIEW

**Comment by mcordingley** [comment]
This PR lets this library work with Laravel 4.x and 5.x and would mean being able to close a few different open issues, as well as remove the reason for the existence of several of the forks of this library.

Looks like people are working around using this library until this happens: https://packagist.org/packages/radic/tmp-underscore-php

**Comment by Anahkiasen** [comment]
I'm not sure I get the rationale, couldn't the dependency be made to accept `4.*|5.*`? The class remains the same, it would extend it either way, no?

**Comment by mcordingley** [comment]
Probably. Suppose Laravel 6 comes out and makes a breaking change to the
class that you inherit from, though. I'm not against code having
dependencies, but for the majority of your users this is going to
effectively be a circular dependency. None of the code from Laravel is
written to be depended upon by non-Laravel code, because it makes no
guarantees of stability across major versions. If you were to merge this
pull, you'd never have to worry about what the Laravel project is doing
again.

The other, less practical argument is that the dependency graph for any
given project should be in a nice, tree shape. If you regard Laravel as a
single entity (because it behaves that way, in spite of the sub-tree
splits), that graph will contain a cycle. Even if you regard Laravel as a
miniature dependency graph of its own, you still have a node in that tree
that's nearly a leaf pointing back up the graph to supposedly more general
code.

To be clear, I think Laravel has some really fantastic helper functions
that should go into more general use, but those should be by way of some
combination of splitting them into packages that are formally split off
from Laravel and some RFCs to the PHP language, itself. It's just that
they're still formally a part of the framework that leaves me feeling very
uncomfortable and leads to issues like this cropping up.

On Sat, May 16, 2015 at 6:30 AM, Maxime Fabre <notifications@github.com>
wrote:

> I'm not sure I get the rationale, couldn't the dependency be made to
> accept 4.*|5.*? The class remains the same, it would extend it either
> way, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anahkiasen/underscore-php/pull/56#issuecomment-102605055>
> .
>



-- 
Michael Cordingley
740.707.7809

**Comment by Anahkiasen** [comment]
I'm not sure I see what you mean, `illuminate/support` _is_ its own independant package, it's not tied directly to the Laravel framework and can be used anywhere. 

The reason I'm a little worried about hardcoding all these functions here is that they now have to be maintained on our end too, and they're rather complex functions (random string generation etc.) which if poorly handled can lead to issues. If Laravel then updates its `Str::random` function per example to be more efficient, or fixes a bug in `Str::slug` per example, we wouldn't benefit from it.

**Comment by mcordingley** [comment]
And yet it's tied to the framework release cycle. Like I said, even though
Laravel has sub-tree splits, they all behave as a cohesive unit. As for the
functions, they're actually quite simple. The random string generation, for
example, just gets some random bytes from openssl_random_pseudo_bytes and
then base64 encodes them. Many of the others delegate still to another
implementation. Take a look:
https://github.com/Anahkiasen/underscore-php/pull/56/files

If you're still concerned about additional maintenance, that's completely
valid and you can close this pull. I just see it as a cleaner solution than
trying to span multiple major versions of Laravel in your dependencies.

On Sat, May 16, 2015 at 10:42 AM, Maxime Fabre <notifications@github.com>
wrote:

> I'm not sure I see what you mean, illuminate/support *is* its own
> independant package, it's not tied directly to the Laravel framework and
> can be used anywhere.
>
> The reason I'm a little worried about hardcoding all these functions here
> is that they now have to be maintained on our end too, and they're rather
> complex functions (random string generation etc.) which if poorly handled
> can lead to issues. If Laravel then updates its Str::random function per
> example to be more efficient, or fixes a bug in Str::slug per example, we
> wouldn't benefit from it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anahkiasen/underscore-php/pull/56#issuecomment-102633175>
> .
>



-- 
Michael Cordingley
740.707.7809

**Comment by Anahkiasen** [comment]
Well I guess we already have some stuff copied over from illuminate/support (array stuff if I recall) so, might as well go full on and remove the dependency.

**Comment by Anahkiasen** [comment]
That being said can you copy over the tests from illuminate/support for the functions we copied over here (if there are any)? Also add Taylor as @author in the docblocks of the string class

**Comment by mcordingley** [comment]
Certainly. Would you like the new commits and the current commit rebased
into a single one or kept separate?

On Sat, May 16, 2015 at 12:32 PM, Maxime Fabre <notifications@github.com>
wrote:

> That being said can you copy over the tests from illuminate/support for
> the functions we copied over here (if there are any)? Also add Taylor as
> @author <https://github.com/author> in the docblocks of the string class
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anahkiasen/underscore-php/pull/56#issuecomment-102648818>
> .
>



-- 
Michael Cordingley
740.707.7809

**Comment by mcordingley** [comment]
Also, I brought the functions in as-is. Would you like the style normalized to PSR standards?

**Comment by Anahkiasen** [comment]
Yeah PSR2, and commits squashed, thanks :)

**Comment by mcordingley** [comment]
Happy to. Taylor's differences from PSR annoy me, to be completely honest.

**Comment by mcordingley** [comment]
For the more trivial functions, I just in-lined their implementations into your public functions. Just seemed odd to have a one-line function that does nothing but reference another one-line function, which in turn does nothing but reference some external function. The one exception to this is the `slug` function from the `Str` class. That one has some content to it, but isn't part of your public interface, so I took it protected, instead.

**Comment by mcordingley** [comment]
Also, I would copy over tests, but I your own test suite actually covers these already.

**Comment by Anahkiasen** [comment]
Not sure I get what you mean, Str::slug is public no?

**Comment by mcordingley** [comment]
In the `Str` class that you originally inherited from, sure. But I didn't see mention of it in your documentation and I did see a `slugify` method that you had defined, so I thought that use of `slug` was strictly internal for you, hence updating to a `protected` designation.

**Pull request merged**
